### PR TITLE
Use ament_cmake to repalce mrt_cmake_modules

### LINKED ISSUE #319: Remove dependency of mrt_cmake_modules
There are several issues of using [mrt_cmake_modules](https://github.com/KIT-MRT/mrt_cmake_modules):

1. it's very slow, because it includes lots of unnecessary/unused packages
2. it seems that it still use catkin
3. its `mrt_add_library` does not support STATIC library
4. ...

I can list more issues, big ones, small ones, but generally I think `ament_cmake` or plain `cmake` should be good enough, there is no need to introduce new dependencies.

### PR DESCRIPTION
**Pull request by felixf4xu**
Hi,

This is my attempt to replace mrt_cmake_modules by `ament_cmake` and standard cmake, which tries to fix #319 

I'd like to see if this kind of PR is on the roadmap of this project.

I tested it locally with ros2 rolling, all local `colcon test` passed, but I'd like to see if it breaks any other tests.

Any comment is welcome.

### CODE REVIEW

**Comment by immel-f** [comment]
Thank you for your contribution! Please give us some time to review the pull request

**Comment by poggenhans** [comment]
I appreciate effort you put into this, but to be honest, I don't understand what you are trying to achieve.

A little background: We started `mrt_cmake_modules` before ament existed and as a better version of catkin (albeit smaller) but with more build system support. If we were to reproduce all the features that we get from it with ament, we would have to write a lot of cmake code. As you can already see from the failing tests, it's not that easy.

mrt_cmake_modules gives us:
- ROS1 support (with catkin)
- ROS2 support (with ament)
- conan support
- code covarage metrics
- a sane set of compiler warnings
- clang-tidy linting
- a wide support of boost versions (especially boost::python is very nasty across cmake/python/boost version combinations)
- lean cmakelist.txt

And since it's released for all ros and ros2 versions, installing it basically comes for free via `apt`.

**Comment by felixf4xu** [comment]
Thanks for the feedback.

A big problem of `mrt_cmake_modules` is that it's not standard and it's not used by other packages in ros2 world. 

To me, more specifically, it does not support windows. I have a local working version of `Lanelet2` on Windows, and I'd like to create more PRs when everything is ready, this PR is actually the first step.

Could you keep the PR open for a while? I'd like to check the failing testcases if it's environment issue or the package itself. I might leave ros1 issues as they are and focus on `humble` and forward.

**Comment by poggenhans** [comment]
> A big problem of mrt_cmake_modules is that it's not standard and it's not used by other packages in ros2 world.

Well that's not a showstopper. It is built on top of ament, catkin, conan and cmake, and these are standard tools. Think of it as all the cmake code we would have to write to offer all the features I enumerated above, just moved into a separate project.

> To me, more specifically, it does not support windows

Well that's a different thing. If you need that, why don't you implement that support on the `mrt_cmake_modules` end? I guess you would only need to fix a few system calls here and there. But keep in mind we will most likely never officially support Windows. We won't be able to provide the extra maintenance effort.

**Comment by felixf4xu** [comment]
this PR is closed.
(if anyone is interested in a Windows/cmake version, I have a fork at https://github.com/felixf4xu/Lanelet2-cmake-windows)

**Pull request closed without merging**
