### PR TITLE
plug and play dockerfile

### PR DESCRIPTION
**Pull request by amastrobera**
I found it difficult to test this repo out at the beginning, and I wanted other users to have it easier. This PR adds a dockerfile and refactors the repo structure to quickly launch its dev-env and play with the code examples.

* all lanelet2 modules were moved inside **lanelet2_modules**
* a submodule **mrt_cmake_modules** was addded
* Dockerfile + build/run scripts
* gitignore to ignore temporary folders used by the docker image

### CODE REVIEW

**Comment by poggenhans** [comment]
Thank you for your contribution. Having a dockerfile to simplify the setup is a good idea.

However, organizing everything with git submodules is not an option. It does not play well with the modular structure of catkin. Could you make a PR that works without touching the current layout?

**Comment by amastrobera** [comment]
Hi Fabian,

thank you for your reply. I think I can. I will try to update it shortly. 

Can add some tool to **replace the mrt_cmake_modules** dependency ? It's just a tool to catkin build from what I see ....

**Comment by poggenhans** [comment]
`mrt_cmake_modules` is actually a cmake-pugin that handles most of the cmake-configuration stuff. It reduces the maintenance effort, because every project just needs a generic CMakeLists.txt.

You could have a look at how the travis job [handles it](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/.travis.yml).

**Comment by amastrobera** [comment]
Yes, I saw that file and got inspiration from it. I can make the docker image clone that repo inside of it at build time. That should be ok, right ?

**Comment by m-naumann** [comment]
Can you maybe explain what caused the issues for you to start quickly? If you copy the lines from travis, it should be all set up in some minutes. If not, maybe you could help there?

**Comment by poggenhans** [comment]
> I can make the docker image clone that repo inside of it at build time. That should be ok, right ?

Should be fine. A network connection is required anyways for the apt commands...

**Comment by amastrobera** [comment]
@poggenhans I did the changes. Basically I added a "docker" folder to launch the repo like in Travis, and the rest is the same as before.

**Comment by amastrobera** [comment]
@poggenhans is this PR ok ?

**Comment by poggenhans** [comment]
Sorry I didn't forget you. I just took this as an opportunity to refactor things a bit to make travis use the Dockerfile as well.

Its merged now, Github just doesn't show it because I squashed the commits before merging. I'll close this PR.

**Comment by amastrobera** [comment]
> Sorry I didn't forget you. I just took this as an opportunity to refactor things a bit to make travis use the Dockerfile as well.
> 
> Its merged now, Github just doesn't show it because I squashed the commits before merging. I'll close this PR.

ah I saw. you did it on Ubuntu 18 instead, and added ROS melodic instead. Any reason for that ? Is it because you are trying to move to Python3 ? The bindings aren't being created for python3 yet, if you need some help I can take a look.

**Comment by poggenhans** [comment]
The docker image is build for 18.04 by default, simply because it's the most recent LTS release. But it also works for 16.04. In Travis, both versions are built and tested now.

Python3 is already supported, there is a small section in the [Readme](https://github.com/fzi-forschungszentrum-informatik/Lanelet2#python3) about it.

**Pull request closed without merging**
