### PR TITLE
fix build by including a copy of python dev config 

### PR DESCRIPTION
**Pull request by kopp**
This fixes long standing build issues as described in #361

### CODE REVIEW

**Comment by immel-f** [comment]
If I understood it correctly, you hard copied the entire `python_dev_config` repo into this repository to fix the dependency issues. Would it be possible to pull the correct version in the dockerfile from git during the build instead? That would make things more intuitively documented and nicer from a dependency perspective

**Comment by kopp** [comment]
@immel-f ,  I had to adapt the package in two ways:
- I adapted to the 'new' conan api (I had to make `export` a function rather than a field)
- I removed the tests of that package because they generated issues during the lanelet2 test stage
So we could create a separate repo hosting that modified code and pull and build that, but I think that will add more complexity. But if you really want that, it can be done.

As an alternative, we would host the conan artifact somewhere (as it was done by bincrafters), e.g. by using https://github.com/thejohnfreeman/redirectory and just pull that in as drop-in replacement for the bincrafters one.  But I am not a conan expert and this would probably take some more time to set up/get it to work.

**Comment by poggenhans** [comment]
thank you for pushing this topic! You are right, we definitively need to renew our conan code. I actually started this already a while ago on this branch: https://github.com/poggenhans/Lanelet2/tree/update_conan, and I picked this up again now.

This branch will add support for conan >2.0 and also remove the need for the old `python_dev_config` dependency so it should be a bit cleaner than this PR. I just need a few days to get the CI green.

**Comment by kopp** [comment]
Cool, and it also brings python 3.12!
I'm happy with that as well, if it does not happen too far in the future ;) .  I actually started my digging to get python 3.12 support, which I need.

If your cleaner solution takes longer then expected, could we either
- use my proposed branches to generate a release 1.2.2 that also supports python 3.12 -- even without merging it or
- merge my changes as an intermediate solution until your cleaner solution is done?

**Comment by poggenhans** [comment]
I hope it should be just a matter of a few days. There shouldn't be many problems left. Building for python 3.12 works already, I just need to convince our CI of it.

**Comment by kopp** [comment]
not necessary after #364

**Pull request closed without merging**
