### PR TITLE
Fix typos in tagging documentation

### PR DESCRIPTION
**Pull request by johschmitz**

### CODE REVIEW

**Comment by immel-f** [comment]
Thank you for the contribution, there are indeed quite a lot of typos in the documentation :sweat_smile: 

However, I would leave terms like "Lanelet", "Area", "Linestring" etc. capitalized, as they refer here to specific concepts and objects in Lanelet2. Could you adapt this in your other pull requests as well?

**Comment by m-naumann** [comment]
I'd actually suggest to combine the PRs into one

**Comment by johschmitz** [comment]
First thing is putting the pull requests together is not possible when using the github.com web interface which is quite useful to read the markdown documentation and make edits. Of course theoretically it can be done with additional work but is it worth the effort just to have two commits less?

I was almost expecting the answer about the capitalization. This is quite inconsistent throughout the documents even before my change. Sometimes even in the same sentence. From what I learned about English only proper nouns should be capitalized and I would argue that here we are talking about common nouns which should not be capitalized. I could be wrong but that is my understanding. I am aware of the fact that native German speakers have some trouble with this kind of capitalization rules, including myself. What I find a good "workaround" for the cases when you specifically have to talk about classes in the code then use backticks and write them exactly like they are written/called in the source code. I also did this in my pull request.
Just to project into the possible future: If we can absolutely not come to a consensus about English grammar rules than I could imagine to recreate the pull request and leave out any of the capitalization changes and leave it up to you how to handle this topic.

**Comment by johschmitz** [comment]
That's alright, ultimately it is up to you. I am going to remove my capitalization changes when I find time. Just out of interest, can you point me to a native speaker example where this style is used? I'm really interested since so far the only place where I knew that two styles exist is in headlines/titles.

**Comment by immel-f** [comment]
> That's alright, ultimately it is up to you. I am going to remove my capitalization changes when I find time. Just out of interest, can you point me to a native speaker example where this style is used? I'm really interested since so far the only place where I knew that two styles exist is in headlines/titles.

Thanks, for example in the Kubernetes [docs](https://kubernetes.io/docs/concepts/containers/) this style is used ([see google style guide](https://developers.google.com/style/capitalization))

**Pull request closed without merging**
